### ISSUE TITLE
Pydata gcloud authentication stoped working in colab and throws error "can’t establish a connection to the server at localhost:8082."

### ISSUE THREAD

**Issue by lucascr91** [pydata/pydata-google-auth#57] opened 2022-08-10 15:15 UTC
In a python package that I help develop (https://github.com/basedosdados/mais/), we always use pydata's google cloud authentication so that the user can access our Data Lake using a personal project on GCP. However, since March, this authentication stopped working and now generates the error `can’t establish a connection to the server at localhost:8082.`

To replicate the error, do this in a colab notebook:

```
!pip install basedosdados
import basedosdados as bd
query = 'SELECT id_municipio, nome FROM basedosdados.br_bd_diretorios_brasil.municipio WHERE sigla_uf = "SP"'
sp_municipio = bd.read_sql(query, billing_project_id='your project')
sp = pd.merge(sp, sp_municipio, how='left', left_on='ds_municipio', right_on='nome')
```

Any idea of how we can make this work again. Many of our users use Google Colab, so it's somewhat critical to us to make this work again. Any help will be appreciated.

**Comment by BadToast** [comment] 2022-08-25 19:28
I've been hitting the same issue.  Apparently they changed the default for the **use_local_webserver** variable in the **get_user_credentials** method.  As per the documentation, it should be defaulting to **False** but it no longer is.  If you explicitly specify it works for me:
```python
credentials = pydata_google_auth.get_user_credentials(
    ['https://www.googleapis.com/auth/bigquery'], 
    use_local_webserver=False.  # you need to explicitly add this now
)
```
In your case you're going to have to make sure your package explicitly passes or sets that variable as well I imagine...

**Comment by tswast** [comment] 2022-10-20 19:31
I believe colab recommends you use `google.colab.auth.authenticate_user` or `google.colab.auth.authenticate_service_account` (defined here: https://github.com/googlecolab/colabtools/blob/main/google/colab/auth.py). Unfortunately, `use_local_webserver=False` will stop working in January #54 unless you also provide a client ID and secret for a test desktop app (https://support.google.com/cloud/answer/6158849?hl=en)

**Comment by tswast** [comment] 2022-10-20 19:32
Closing as this is in favor of #54 as unfortunately this is working as intended.

**Closed by tswast** 2022-10-20 19:32 UTC
Labels: type: question
